hide-cursor-when-typing = true

confirm-before-quit = false

[cursor]
shape = 'block'
blinking = false

[editor]
 program = "nvim"
 args = []

[window]
width = 700
height = 500
mode = "windowed"
# opacity = 0.8
blur = true
decorations = "enabled"
colorspace = "display-p3"

# [renderer]
# performance = "high"
# backend = "automatic"
# disable-unfocused-render = false
# level = 1
# filters = ["newpixiecrt"] # balatro like

[fonts]
size = 14

# Doesn't work yet
# [fonts.regular]
# family = "FiraCodeNerdFontMono-Regular"
# style = "Normal"
# weight = 400

# [fonts.bold]
# family = "cascadiamono"
# style = "Normal"
# weight = 800
#
# [fonts.italic]
# family = "cascadiamono"
# style = "Italic"
# weight = 400
#
# [fonts.bold-italic]
# family = "cascadiamono"
# style = "Italic"
# weight = 800

[scroll]
multiplier = 4.0
divider = 1.0

# Example:
[navigation]
mode = "Plain"
clickable = false
hide-if-single = true
use-current-path = true
# Doesn't work, idk why
color-automation = [
  { program = "nvim", color = "#656597" },
  { program = "pacman", color = "#ddad66" }
]

# Example 4 for MacOS with tmux installed by homebrew
# [shell]
# program = "/opt/homebrew/bin/tmux"
# args = ["new-session", "-c", "/var/www"]

[colors]
background = '#19171D'
foreground = '#F2E1E2'
selection-background = '#262029'
selection-foreground = '#E8B8C5'
cursor = '#FEBDD4'
black = '#0F0D12'
red = '#D2717F'
green = '#EDFDE2'
yellow = '#F4D29B'
blue = '#86ADCC'
magenta = '#C7B8E1'
cyan = '#BFE4DF'
white = '#F2E1E2'
light_black = '#141218'
light_red = '#FEBDD4'
light_green = '#E9F6CA'
light_yellow = '#E9AB8C'
light_blue = '#B1DBC9'
light_magenta = '#9b5953'
light_cyan = '#F7BAE2'
light_white = '#FAD9ED'

[bindings]
keys = [
  # Enable VI mode on escape, when not in VI mode.
  # { key = "esc", mode = "~vi", action = "ToggleVIMode" },

  # Panel split
  { key = "r", with = "super | shift", action = "SplitRight" },
  { key = "d", with = "super | shift", action = "SplitDown" },

  # Panel resize actions
  { key = "k", with = "super | shift", action = "MoveDividerUp" },
  { key = "j", with = "super | shift", action = "MoveDividerDown" },
  { key = "l", with = "super | shift", action = "MoveDividerLeft" },
  { key = "h", with = "super | shift", action = "MoveDividerRight" },
]
# More information in: https://raphamorim.io/rio/docs/key-bindings
